import SetupUserType from "@/src/screens/auth/setup-user-type";

export const metaData = {
  title: "User profile type",
  description: "Generated by create next app",
};

const page = () => {
  return <SetupUserType />;
};

export default page;
