import { SetNewPasswordScreen } from "@/src/screens/auth";

export const metadata = {
    title: "Verify Code",
    description: "Generated by create next app",
};

const page = () => {
    return <SetNewPasswordScreen />
};

export default page;
