import { ForgotPasswordScreen } from "@/src/screens/auth";

export const metadata = {
    title: "Forgot Password",
    description: "Generated by create next app",
};

const page = () => {
    return <ForgotPasswordScreen />
};

export default page;
