import "./globals.css";
import { Poppins, Montserrat } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/src/auth";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "../auth/jwt";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

export default async function RootLayout({ children }) {
  const session = await auth();
  console.log("this is session : ", session?.user);
  return (
    <SessionProvider session={session}>
      <html lang="en" className={`${poppins.variable} ${montserrat.variable}`}>
        <body className="font-poppins">
          <AuthProvider>
            <Toaster position="top-right" reverseOrder={false} />
            {children}
          </AuthProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
