import "./globals.css";
import { Poppins, Montserrat, } from 'next/font/google'
import LocalFont from 'next/font/local'
export const metadata = {
  title: "Hotel Buuk",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});


const lemonMilk = LocalFont({
  src: [
    {
      path: '../../public/assets/fonts/LEMONMILK-Regular.otf',
      weight: "400",
    },
    {
      path: '../../public/assets/fonts/LEMONMILK-Medium.otf',
      weight: "500",
    },
    {
      path: '../../public/assets/fonts/LEMONMILK-Bold.otf',
      weight: "700",
    },
  ],
  variable: '--font-lemonMilk'
})


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${lemonMilk.className} ${poppins.variable} ${montserrat.variable}`}>
      <body className="font-poppins">
        {children}
      </body>
    </html>
  );
}
