import { LoginScreen } from "@/src/screens/auth";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

const page = () => {
  return <LoginScreen />
};

export default page;
