import { SignUpScreen } from "@/src/screens/auth";

export const metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

const page = () => {
  return <SignUpScreen />;
};

export default page;
