export const hotels = [
    {
        id: 1,
        hotelName: "Superman Hotel",
        city: "London",
        country: "United Kingdom",
        price: "$5,815",
        guestType: "Business Guest",
        event: "Business Tour | Manufacturing London Market Tour",
        dateRange: "Mar 2 - Mar 4, 2025",
        imageUrl: "/assets/images/hotel-1.png",
        isFavorite: false,
    },
    {
        id: 2,
        hotelName: "Superman Hotel",
        city: "London",
        country: "United Kingdom",
        price: "$5,815",
        guestType: "Business Guest",
        event: "Business Tour | Manufacturing London Market Tour",
        dateRange: "Mar 2 - Mar 4, 2025",
        imageUrl: "/assets/images/hotel-2.png",
        isFavorite: true,
    },
    {
        id: 3,
        hotelName: "Superman Hotel",
        city: "London",
        country: "United Kingdom",
        price: "$5,815",
        guestType: "Business Guest",
        event: "Business Tour | Manufacturing London Market Tour",
        dateRange: "Mar 2 - Mar 4, 2025",
        imageUrl: "/assets/images/hotel-3.png",
        isFavorite: false,
    },
    {
        id: 4,
        hotelName: "Superman Hotel",
        city: "London",
        country: "United Kingdom",
        price: "$5,815",
        guestType: "Business Guest",
        event: "Business Tour | Manufacturing London Market Tour",
        dateRange: "Mar 2 - Mar 4, 2025",
        imageUrl: "/assets/images/hotel-4.png",
        isFavorite: true,
    },
    {
        id: 5,
        hotelName: "Superman Hotel",
        city: "London",
        country: "United Kingdom",
        price: "$5,815",
        guestType: "Business Guest",
        event: "Business Tour | Manufacturing London Market Tour",
        dateRange: "Mar 2 - Mar 4, 2025",
        imageUrl: "/assets/images/hotel-1.png",
        isFavorite: false,
    },
    {
        id: 6,
        hotelName: "Superman Hotel",
        city: "London",
        country: "United Kingdom",
        price: "$5,815",
        guestType: "Business Guest",
        event: "Business Tour | Manufacturing London Market Tour",
        dateRange: "Mar 2 - Mar 4, 2025",
        imageUrl: "/assets/images/hotel-2.png",
        isFavorite: true,
    },
];