import SetupBasicInfoNomad from "@/src/screens/auth/setup-basic-info";

export const metaData = {
  title: "User profile basic info",
  description: "Generated by create next app",
};

const page = () => {
  return <SetupBasicInfoNomad />;
};

export default page;
